### ISSUE TITLE
Allow to change WiFi configuration

### ISSUE THREAD

**Issue by marcelstoer** [sebastianhodapp/ESPbootloader#4]
It'd be helpful to change the WiFi configuration even if an SSID is already set. However, I don't know what the best option for enabling this is.
What's the behavior if you transfer the ESP to a different WiFi and boot it? In this case it _does_ have a configuration but it can't connect to the selected SSID.

**Comment by 3rw1n70** [comment]
Marcel,

I changed the code so it does exactly that, see **bold code** below:
_===========code start ================_
**iWifiTries = 0    -- Counter of tries to connect to wifi**
**iMaxTries = 10    -- Maximum number of tries while waiting for connection**

if pcall(function () 
    dofile("config.lc")
end) then
**print("Connecting to SSID("..ssid..")")**
    wifi.setmode(wifi.STATION)
    wifi.sta.config(ssid,password)
    wifi.sta.connect()
    tmr.alarm(1, 1000, 1, function() 
        if wifi.sta.getip() == nil then
**print("SSID("..ssid..")["..iWifiTries.."]")**
**iWifiTries = iWifiTries + 1**
**if ( iWifiTries > iMaxTries ) then**
**print("Not able to connect to predefined WIFI so deleting config.lc file")**
**file.remove("config.lc")**
**node.restart()**
end
        else
            tmr.stop(1)
            print("Connected, IP is "..wifi.sta.getip())
            dofile("run_program.lua")
        end
    end)
else
    print("Enter configuration mode")
    dofile("run_config.lua")
end
_========== code end ============_

Tried to indent the code using the Mastering Markdown 3 minute read, but think I missed something...

Anyway hope you get the point,

Erwin

**Comment by timoline** [comment]
may I suggest you do a pull requestlat https://github.com/huelvayork/ESPbootloader
as for now...it lookslike this repo isn't updated anymore....

lets work together on 1 repo !

**Comment by sebastianhodapp** [comment]
Of course. I'm just short in time at the moment :-(

**Comment by sebastianhodapp** [comment]
Solved via setting GIO0 to low within the first seconds after booting.

**Comment by tobiasbader** [comment]
@sebastianhodapp could you make a commit for this change?
